name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '4', '6', '8', '10', '12' ]
      fail-fast: false
    name: Test with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        
      - name: Install dependencies
        run: npm install

      - name: Test
        env:
          BBY_API_KEY: XXX
          NO_UPDATE_NOTIFIER: 1
        run: npm test
